export const caseStudies = [
  {
    id: 1,
    title: "Drova's Journey from Salesforce Complexity to Zoho CRMPlus Simplicity",
    company: "Drova",
    industry: "CRM & Business Systems",
    tag: "Zoho CRM Plus",
    image: "/images/Case-Study/Drova1.png",
    slug: "drova-zoho-crm-plus-case-study",
    highlight: "CRM Migration",
    color: "#3B82F6",
  },
  {
    id: 2,
    title: "Digitizing Port Logistics & Manufacturing for Silk Logistics with Zoho One",
    company: "Silk Logistics",
    industry: "Logistics & Manufacturing",
    tag: "Zoho One",
    image: "/images/Case-Study/silk-logistic.png",
    slug: "silk-logistics-zoho-one-case-study",
    highlight: "Port & Manufacturing",
    color: "#10B981",
  },
  {
    id: 3,
    title: "Transforming Visual Exposure's Operations with Zoho One",
    company: "Visual Exposure",
    industry: "Media & Marketing",
    tag: "Zoho One",
    image: "/images/Case-Study/Visual-expo1.png",
    slug: "visual-exposure-zoho-one-case-study",
    highlight: "Digital Operations",
    color: "#F59E0B",
  },
  {
    id: 4,
    title: "Silk Contract Logistics Zoho Desk Case Study",
    company: "Silk Contract Logistics",
    industry: "Logistics",
    tag: "Zoho Desk",
    image: "/images/Case-Study/silk-logistic.png",
    slug: "silk-contract-logistics-zoho-desk",
    highlight: "Customer Support",
    color: "#10B981",
  },
  {
    id: 5,
    title: "Silk Contract Logistics Zoho Expense Case Study",
    company: "Silk Contract Logistics",
    industry: "Logistics",
    tag: "Zoho Expense",
    image: "/images/Case-Study/silk-logistic.png",
    slug: "silk-contract-logistics-zoho-expense",
    highlight: "Expense Management",
    color: "#10B981",
  },
  {
    id: 6,
    title: "Zoo Business Media Case Study",
    company: "Zoo Business Media",
    industry: "Media & Publishing",
    tag: "Zoho Platform",
    image: "/images/Case-Study/Zoo.png",
    slug: "zoo-business-media-case-study",
    highlight: "Media Digitisation",
    color: "#8B5CF6",
    logoScale: 1.5,
  },
  {
    id: 7,
    title: "BlueNRG Zoho One Case Study",
    company: "BlueNRG",
    industry: "Energy & Renewables",
    tag: "Zoho One",
    image: "/images/Case-Study/Blue.png",
    slug: "bluenrg-zoho-one-case-study",
    highlight: "Energy Operations",
    color: "#F97316",
    logoScale: 1.5,
  },
  {
    id: 8,
    title: "Civil Survey Solutions Case Study",
    company: "Civil Survey Solutions",
    industry: "Engineering & Construction",
    tag: "Zoho Platform",
    image: "/images/Case-Study/Civil.png",
    slug: "civil-survey-solutions-case-study",
    highlight: "Field Operations",
    color: "#6B7280",
    logoScale: 1.5,
  },
  {
    id: 9,
    title: "Enhancing Drova's Sales and Support Processes with Zoho Solutions",
    company: "Drova",
    industry: "CRM & Business Systems",
    tag: "Zoho CRM",
    image: "/images/Case-Study/Drova1.png",
    slug: "enhancing-drovas-sales-and-support-processes-with-zoho-solutions",
    highlight: "Sales & Support",
    color: "#3B82F6",
  },
  {
    id: 10,
    title: "My Autonomy – Client Overview",
    company: "My Autonomy",
    industry: "Financial Services",
    tag: "Business Systems",
    image: "/images/Case-Study/Autonomy.png",
    slug: "my-autonomy-client-overview",
    highlight: "Autonomy Platform",
    color: "#EF4444",
    logoScale: 1.5,
  },
  {
    id: 11,
    title: "Responsive Lending",
    company: "Responsive Lending",
    industry: "Mortgage & Finance",
    tag: "Digital Transformation",
    image: "/images/Case-Study/Responsive.png",
    slug: "responsive-lending",
    highlight: "Lending Platform",
    color: "#EC4899",
    logoScale: 1.5,
  },
  {
    id: 12,
    title: "Safe Gauge Enhances Operations Using Zoho Creator",
    company: "Safe Gauge",
    industry: "Safety & Operations",
    tag: "Zoho Creator",
    image: "/images/Case-Study/Safe-gauge.png",
    slug: "safe-gauge-enhances-operations-using-zoho-creator",
    highlight: "Safety Systems",
    color: "#14B8A6",
    logoScale: 1.5,
  },
  {
    id: 13,
    title: "Visual Exposure's Digital Transformation with Zoho One",
    company: "Visual Exposure",
    industry: "Media & Marketing",
    tag: "Zoho One",
    image: "/images/Case-Study/Visual-expo1.png",
    slug: "visual-exposures-digital-transformation-with-zoho-one",
    highlight: "Full Transformation",
    color: "#F59E0B",
  },
];
